URL:
  change_state: /statemachine/input
  get_state: /statemachine/state
  notification: /notifications
  protocol: http://
  address: 127.0.0.1

node:
  time:
    starting: 10
    running: 10
    shutdown: 20
    get: 10
  port:
    # range min - max need to be at least 10 000
    min: 10000
    max: 60000
    default: 20000
  depth:
    # values have to be non negative
    min: 0
    max: 5 # cannot be bigger than 5
    default: 0
  children:
    min: 1 # cannot be smaller than 1
    max: 10 # cannot be bigger than 10
    default: 3

architecture: MOM

rabbitmq:
  rpc_timeout: 21
  validation: true
  envelope_format: proto # supported formats are either json either proto (Protocol Buffer)

REST:
  timeout: 21
  pydantic: true

debug: True

measurement:
  architecture:
  - MOM
  - REST
  runs: 10
  tree:
    children: 3
    depth: 2
  write: false
