URL:
  address: 127.0.0.1
  change_state: /statemachine/input
  get_state: /statemachine/state
  notification: /notifications
  protocol: http://
architecture: MOM
debug: true
node:
  children:
    default: 3
    max: 10
    min: 1
  depth:
    default: 0
    max: 5
    min: 0
  port:
    default: 20000
    max: 60000
    min: 10000
  time:
    get: 10
    running: 10
    shutdown: 20
    starting: 10
rabbitmq:
  rpc_timeout: 21
